name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploying to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/Services/Personal/dev.bykowskiolaf.blog
            git pull --rebase
            docker compose up --build -d